var PacmanMAP = [];
PacmanMAP[0] =
"\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
X0....................................0X\
X...XXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXX.X\
X......................................X\
X.XXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXX.X\
X.XXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXX.X\
X.XXXX........XXXXX.XXXXX........XXXXX.X\
X.XXXX.XXXXXX.XXXXX.XXXXX.XXXXXX.XXXXX.X\
X.XXXX.XXXXXX.XXXXX.XXXXX.XXXXXX.XXXXX.X\
X.XXXX.XXXXXX.XXXXX.XXXXX.XXXXXX.XXXXX.X\
X......................................X\
X.XXXX.XXXXXX.XXXXX.XXXXX.XXXXXX.XXXXX.X\
X.XXXX.XXXXXX.XXXXX.XXXXX.XXXXXX.XXXXX.X\
X.XXXX.XXXXXX.XXXXX.XXXXX.XXXXXX.XXXXX.X\
X.XXXX........XXXXX.XXXXX........XXXXX.X\
X.XXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXX.X\
X.XXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXX.X\
X......................................X\
X.XXXXX.XXXXXXXXXXX0XXXXXX.XXXXXXXXXXX0X\
X.XXXXX.XXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXX\
X.......XXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXX\
XXXXXXX..........................XXXXXXX\
XXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXX\
XX......XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXX\
XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXX\
XX....XXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXX\
X......................................X\
X.XXXXX.XXXXXXXXXXX.XXXXXXXXXXXXXXXXXX.X\
X0....................................0X\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
";
function level(a){
    return PacmanMAP[a];
}